databases:
  - name: footballreview
    databaseName: football
    user: zablon

services:
  - type: web
    name: footballreview
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: footballreview
          property: connectionString
      - key: e45d2f9aa0a00627c63bae8ce7fbca7f
        sync: false
